### ISSUE TITLE
[Request] Clear Inactive Timer on Infograph Modular

### ISSUE THREAD

**Issue by shotnine** [SniperGER/LockWatch2#10]
At this time, the timer always seems to show the last set timer, even if it’s inactive.

Would it be possible to clear this, or perhaps display an alternate widget if no timer is set?

Either way, thanks for taking the time to develop this.

**Comment by SniperGER** [comment]
As far as I know (i just have a Series 3), this behavior is actually intended as-is. I personally don't see the point in replacing the complication just because the last timer is inactive.

**Comment by shotnine** [comment]
Ahh, I see. Thanks for the response!
