### ISSUE TITLE
LocalWatch2 covers notifications

### ISSUE THREAD

**Issue by izhangxm** [SniperGER/LockWatch2#13]
**Describe the bug**
when I set a scale(>1) or set a case to LockWatch2, it will cover other notifications and result in unexpected effect.
Here is a video.
https://photos.app.goo.gl/yoVCd1cHR2jyTb7M8

**To Reproduce**
_Steps to reproduce the behavior:_
1. Go to settings --> LockWatch2 --> Advanced --> Position --> PORTRAIT
2. Click on  Scale
3. input a value 1.32
4. See error on notification interface.

**Expected behavior**
All other notifications should be at bottom of LockWatch2 and can not be covered by LocalWatch2.

**Screenshots**
![image](https://user-images.githubusercontent.com/16874796/104812180-7853ba80-583b-11eb-9097-067d734a53e8.png)

**Device Information (please complete the following information):**
 - Model: iPhone xs
 - iOS Version: 13.5
- Jailbreak: unc0ver 5.3.1; substitute 2.0.4

**Comment by SniperGER** [comment]
Thank you for your report! I'm currently rewriting LockWatch to support iOS 14, and this will actually be part of the update.

There is no ETA yet, it's just too many unexpected issues right now.

**Comment by izhangxm** [comment]
Thank you very much! This is a really nice work.
