### ISSUE TITLE
Unable to Customize LockWatch’s face

### ISSUE THREAD

**Issue by harshsingh7** [SniperGER/LockWatch2#3]
Tried Touch and hold on the watchface but doesn’t do anything. Tried 3D touching, it zooms out with customize button but can’t press it, it goes back to being whatever it is. Switching Watch sizes Sometimes work, other times just shows nothing. Here’s a video demo: 
https://photos.app.goo.gl/ujGPxt7Z21Lwkbfy7

**Comment by SniperGER** [comment]
From the video, it looks like you have a 3D Touch based wallpaper (a live Live Wallpaper?). Can you please try using a static wallpaper and see if that makes any difference?

**Comment by harshsingh7** [comment]
Just tried it with Static wallpaper and removing XenHTML . Still the same issues, unable to Customize

**Comment by SniperGER** [comment]
Confirmed working the other way round: a live wallpaper let's me 3D Touch just fine.

Anyways, the watch disappearing is cause by switching from Series 5 Faces to Series 3. Older watches don't have some faces, which is why it disappears (and I included the "Reset Watch Faces" button just for this case, including the note beneath it).

And other than my device being an iPhone X and yours a Xs Max, I don't see any obvious differences between us except some lock screen tweaks. Try to disable anything except LockWatch, though this might not work either.

**Comment by harshsingh7** [comment]
Just tried disabling anything related to lock screen, and only enabling LockWatch, no luck. Gonna try Restoring RootFS and only install LockWatch

**Comment by harshsingh7** [comment]
Just finished resting and restored to my previous setup. Unfortunately, still no luck. Not able to customize .

**Comment by SniperGER** [comment]
Restoring your RootFS just to make a tweak hopefully work. Wow, that's brave...

Anyways, I'll provide a debug build that shows you the force values as you press it once I figure out how to do it properly.

**Comment by harshsingh7** [comment]
Sounds good. Will be waiting

**Comment by SniperGER** [comment]
Here's a debug build that will show the current `force` value while you press, which is supposed to be a value between 0 and 1.2. If LockWatch recognizes the force being larger or equal 1, the text will turn green. (This is not the same as the value itself being 1 or higher, this is specifically asking LockWatch if it recognized this value).

Additionally, there are `forceTouchCapability` and `usingLongPress`, which _should_ be 1 and 0 respectively on your device.

Once you end the force touch there's the `latched` value, which again asks LockWatch if the force was sufficient for enabling the switcher. This will probably be 0 in your case, but it's just there for the record.

[ml.festival.lockwatch2_2.0b2-2+debug_iphoneos-arm.deb.zip](https://github.com/SniperGER/LockWatch2/files/4421179/ml.festival.lockwatch2_2.0b2-2%2Bdebug_iphoneos-arm.deb.zip)

Unfortunately, as GitHub doesn't allow me to upload .deb files directly, this is packed again in a zip file.

**Comment by harshsingh7** [comment]
Testing right now. Will give you the progress in edits of this comment

**Comment by SniperGER** [comment]
Interesting. The force value doesn't seem to go above 1.00000, while it's supposed to show a maximum of 1.20000. This might be a first clue to what is happening here.

**Comment by harshsingh7** [comment]
Found a FiX!!!!

Went to Settings->Accessibility->Touch->3D Touch And changed the 3D Touch Sensitivity to medium. It was “Firm” before which is 1 max. Put it to medium and which is 1 and the reading in debug build is 1.2 and it turns green and it stays on in customizing state.

**Comment by SniperGER** [comment]
That's great to hear! Now I just have to adapt LockWatch to use any sensitivity setting. Thank you so much for this!

**Comment by harshsingh7** [comment]
No problem at all. Bring a small programmer as well, I know how much the final product matters and polishing it could be hard. 

BTW, is it possible to get a transparent background at the back of clock digits instead of grey?
![ED231BBB-B868-4F4E-BBCC-B9F1A38F86C1](https://user-images.githubusercontent.com/24804295/78255597-7e072c00-74c5-11ea-859f-4109cff3e689.png)

**Comment by SniperGER** [comment]
Yes, this has been implemented in 2.0b2-1. You can find it within "Advanced" in LockWatch preferences.

**Comment by harshsingh7** [comment]
The Liquid Metal and Vapour watchface won’t show anything 
![4ED72583-E85D-4AE0-B889-67C067C7753B](https://user-images.githubusercontent.com/24804295/78256240-4351c380-74c6-11ea-8958-547c940612b8.png)
![152FE931-ED8B-441F-BA68-AB4A6B5927A1](https://user-images.githubusercontent.com/24804295/78256255-48af0e00-74c6-11ea-93bc-6313f183b93a.png)

**Comment by SniperGER** [comment]
> The Liquid Metal and Vapour watchface won’t show anything

This is a known issue and requires even more files to be copied from watchOS, but I didn't have a chance to test if this even works. Currently, fixing 3D Touch and adding Complications are my priorities.

**Comment by harshsingh7** [comment]
Well, I’m really glad I was able to help out in fixing some stuff, and it’s one of my favorite lockscreen tweaks. Keep up with your great work and have fun developing.

**Comment by harshsingh7** [comment]
Sorry to disturb, but another possible UI glitch!?
![0947BED9-EAE4-4E61-BD9D-8C168A1298D0](https://user-images.githubusercontent.com/24804295/78258147-cf64ea80-74c8-11ea-9efc-cf967f512e87.png)

**Comment by SniperGER** [comment]
Fixed both your issues (3D Touch and the layout glitch) in code. Build will be up on the repo in a few minutes.
