### ISSUE TITLE
[i7+ 13.3.1] I don’t see anything 🤪

### ISSUE THREAD

**Issue by Oxtie** [SniperGER/LockWatch2#4]
Hi,.. 
I already have analog watches on lock screen (XenHTML > MadWidgets) and while I was searching for new watches, I found this tweak 😃 however, upon installation, I see nothing else then my previous analog clock).

Possible conflict with XenHTML? 🤔 

I’m on iPhone7+ with iOS 13.3.1

I’m always looking for these in lock screen widgets or tweaks:
Date, Day, Time, Battery and SystemStat (NetSpeed, Ram, Disk, CPU). “Time” tweak shows most of these but I’m hunting for analog clock 😍

**Comment by SniperGER** [comment]
Just tried it myself, definitely no conflict with Xen HTML on my side.

**Comment by harshsingh7** [comment]
Tried it on my side with XenHTML and MadWidgets, if anything, LockWatch is placed above XenHTML Widgets. BTW, I just noticed, LockWatch takes away the Day and Date. Only thing that remains is the clock/Time.

**Comment by Oxtie** [comment]
🥵 I hated that day/date anyways, that’s why “Time” tweak allows me set Date, Time, Day and 00.0KB/s on status bar 😋

Mad widget gives analog clocks but also adds day date etc 🥵 after finding another widget, I could set a translucent analog (which is great thus far)
![948B585B-6708-4379-A305-12777CD0F96A](https://user-images.githubusercontent.com/1399659/78378204-b734be80-75e1-11ea-9de8-da3d3411bb5e.png)

**Comment by harshsingh7** [comment]
I have a XS MAX so I’m unable to put too much stuff in the status bar. Gotta say, your setup Looks pretty cool. Here’s a pic of mine. Just missing the day date
![BFCBF9DA-2B68-4E24-80CE-8E43B4BED2EB](https://user-images.githubusercontent.com/24804295/78378604-305ef200-759f-11ea-9193-85fe141dd4c1.png)

**Comment by Oxtie** [comment]
Then in your case,.. MadWidgets are suppose get the job done 🤔 why don’t you try it? 
![BCFD6874-417C-455E-9D16-E78DB0E8AF20](https://user-images.githubusercontent.com/1399659/78381001-c584d980-75e5-11ea-8d78-e1727b0a84f6.png)

**Comment by harshsingh7** [comment]
The thing is, I really love LockWatch’s approach, MadWidgets don’t just have a widget that contains just Day, Date

**Comment by Oxtie** [comment]
🤪 I would also like it (if only it shows up on my lock screen) but for now,.. I’ve to assume it won’t (till the conflict is caught)
